fix #18 by making `query_command` shell-agnostic
f-person/auto-dark-mode.nvim pull request #19
Opened 2024-02-27 16:18 UTC by bugabinga

`query_command` is now of type `table` so that `vim.fn.jobstart` does
not use `shell`.

2024-02-29 20:36 UTC, nekowinston commented on lua/auto-dark-mode/init.lua
> +			query_command = vim.tbl_extend("keep", { "su", "-", "$SUDO_USER", "-c" }, query_command)
I'm unsure how this command will behave now.
It seems like `su` will spawn the default shell indicated in `/etc/passwd`?

2024-03-01 00:08 UTC, nekowinston requested changes
This PR so far (with my suggestions applied) breaks the plugin on Linux/NixOS for me.

I'll take another look on Linux and macOS tomorrow.

2024-04-13 20:20 UTC, f-person commented
Hey @nekowinston! Does your commit fix the issues with the PR? Feel free to merge this if it works for you or close it otherwise :)

2024-04-13 20:34 UTC, nekowinston commented
It doesn't my commit so far was a simple syntax error fix, the whole PR doesn't work for me in its current state.
I meant to get back to this, but I currently don't have much time for FOSS work... 😓

2024-04-13 22:02 UTC, f-person commented
No worries, do as you wish whenever you wish with this one :)

2024-05-03 16:37 UTC, bugabinga commented
I have tested this branch on Windows, WSL and Fedora 40 and those work.
Unfortunately, I have no NixOs system to test on.

2024-10-09 14:52 UTC, nekowinston commented
Sorry for taking ages to get to this! :sweat: 
Going to try this on my other machines; will merge it should everything work well.

2024-10-09 16:28 UTC, nekowinston approved these changes
Successfully tested on:
- Linux/NixOS
- macOS Sequoia
- Windows 10
- WSL

and again, thanks for your contribution 😄

2024-10-09 16:28 UTC, merged